"""add index to vaults in chunks

Revision ID: 3d02bd5ee674
Revises: 421b3f9d0f37
Create Date: 2026-03-31 17:46:31.389609

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d02bd5ee674"
down_revision: str | Sequence[str] | None = "421b3f9d0f37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_chunks_vault_id"), "chunks", ["vault_id"], unique=False)
    op.alter_column(
        "files",
        "file_type",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "PDF",
            "IMAGE",
            "DOCX",
            "TXT",
            "NOTE",
            name="validfiletypesenum",
            native_enum=False,
            length=50,
        ),
        existing_nullable=False,
        postgresql_using="file_type::varchar",
    )
    op.alter_column(
        "files",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.Enum(
            "PENDING",
            "PROCESSING",
            "READY",
            "FAILED",
            name="filestatusenum",
            native_enum=False,
            length=50,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'PROCESSING'::text"),
        postgresql_using="status::varchar",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "PROCESSING",
            "READY",
            "FAILED",
            name="filestatusenum",
            native_enum=False,
            length=50,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'processing'::text"),
    )
    op.alter_column(
        "files",
        "file_type",
        existing_type=sa.Enum(
            "PDF",
            "IMAGE",
            "DOCX",
            "TXT",
            "NOTE",
            name="validfiletypesenum",
            native_enum=False,
            length=50,
        ),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_chunks_vault_id"), table_name="chunks")
    # ### end Alembic commands ###
