"""add thumbnail to vaults

Revision ID: 533413d72a6f
Revises: 3d02bd5ee674
Create Date: 2026-04-30 11:29:23.934934

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "533413d72a6f"
down_revision: str | Sequence[str] | None = "3d02bd5ee674"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vaults",
        sa.Column(
            "thumbnail_url",
            sa.String(500),
            nullable=True,
            comment="URL to vault thumbnail image",
        ),
    )

    op.create_index("ix_vaults_thumbnail_url", "vaults", ["thumbnail_url"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vaults", "thumbnail_url")
