/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultVaultIdRouteImport } from './routes/vault/$vaultId'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppGenerateRouteImport } from './routes/_app/generate'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppWorkshopIndexRouteImport } from './routes/_app/workshop/index'
import { Route as AppWorkshopVaultIdRouteImport } from './routes/_app/workshop/$vaultId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultVaultIdRoute = VaultVaultIdRouteImport.update({
  id: '/vault/$vaultId',
  path: '/vault/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopIndexRoute = AppWorkshopIndexRouteImport.update({
  id: '/workshop/',
  path: '/workshop/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopVaultIdRoute = AppWorkshopVaultIdRouteImport.update({
  id: '/workshop/$vaultId',
  path: '/workshop/$vaultId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof AppDocumentsRoute
  '/generate': typeof AppGenerateRoute
  '/home': typeof AppHomeRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
  '/workshop/$vaultId': typeof AppWorkshopVaultIdRoute
  '/workshop/': typeof AppWorkshopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof AppDocumentsRoute
  '/generate': typeof AppGenerateRoute
  '/home': typeof AppHomeRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
  '/workshop/$vaultId': typeof AppWorkshopVaultIdRoute
  '/workshop': typeof AppWorkshopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/generate': typeof AppGenerateRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
  '/_app/workshop/$vaultId': typeof AppWorkshopVaultIdRoute
  '/_app/workshop/': typeof AppWorkshopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/generate'
    | '/home'
    | '/settings'
    | '/login'
    | '/vault/$vaultId'
    | '/workshop/$vaultId'
    | '/workshop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/generate'
    | '/home'
    | '/settings'
    | '/login'
    | '/vault/$vaultId'
    | '/workshop/$vaultId'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/documents'
    | '/_app/generate'
    | '/_app/home'
    | '/_app/settings'
    | '/_auth/login'
    | '/vault/$vaultId'
    | '/_app/workshop/$vaultId'
    | '/_app/workshop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  VaultVaultIdRoute: typeof VaultVaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$vaultId': {
      id: '/vault/$vaultId'
      path: '/vault/$vaultId'
      fullPath: '/vault/$vaultId'
      preLoaderRoute: typeof VaultVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generate': {
      id: '/_app/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshop/': {
      id: '/_app/workshop/'
      path: '/workshop'
      fullPath: '/workshop/'
      preLoaderRoute: typeof AppWorkshopIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshop/$vaultId': {
      id: '/_app/workshop/$vaultId'
      path: '/workshop/$vaultId'
      fullPath: '/workshop/$vaultId'
      preLoaderRoute: typeof AppWorkshopVaultIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkshopVaultIdRoute: typeof AppWorkshopVaultIdRoute
  AppWorkshopIndexRoute: typeof AppWorkshopIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppHomeRoute: AppHomeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkshopVaultIdRoute: AppWorkshopVaultIdRoute,
  AppWorkshopIndexRoute: AppWorkshopIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  VaultVaultIdRoute: VaultVaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
